name: stepper_list_view
description: StepperListView is an widget that building the list ui with stepper widget.
version: 1.0.0
homepage: https://github.com/subhashDev11/stepper_list_view

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

screenshots:
  - description: 'Examples of Listing-1.'
    path: example/screenshots/scr1.png
  - description: 'Examples of Listing-2.'
    path: example/screenshots/scr2.png